<?php

/**
 * @file
 * Loads dynamic blocks on cached page for anonymous users by performing AJAX request.
 */

/**
 * Implements hook_menu().
 */
function ajaxblocks_menu() {
  $items = array();
  $items['ajaxblocks'] = array(
    'title' => 'Ajax blocks',
    'page callback' => 'ajaxblocks_ajax_handler',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_config_info().
 */
function ajaxblocks_config_info() {
  $prefixes['jaxblocks.settings'] = array(
    'label' => t('Ajax Blocks settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Adds AJAX settings to the block configure page.
 */
function ajaxblocks_form_layout_block_configure_form_alter(&$form, &$form_state) {
  // Retrieve current setting for this block.
  $block = $form_state['block'];
  $settings = config_get('ajaxblocks.settings', $block->module . ':' . $block->delta . ':' . $block->uuid);

  // AJAX settings fieldset.
  $form['block_settings']['ajaxblocks'] = array(
    '#type' => 'fieldset',
    '#title' => t('AJAX settings'),
    '#description' => t('The settings for loading the block via AJAX request made after the page loading. This method is used for anonymous user only, and the whole page must be cached.'),
    '#weight' => 60,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'visibility',
  );

  if (module_exists('authcache')) {
    $form['block_settings']['ajaxblocks']['warning'] = array(
      '#type' => 'markup',
      '#value' => t('Authcache module is installed. Please check <a href="@settings">settings</a> and make sure it does not cache AJAX requests to page (Backdrop path) "ajaxblocks".',
        array('@settings' => url('admin/config/development/performance/authcache'))),
    );
  }

  $form['block_settings']['ajaxblocks']['is_ajax'] = array(
    '#type' => 'radios',
    '#title' => t('Load block via AJAX'),
    '#description' => t("Select 'yes' if this block has dynamic content and isn't displayed correctly on cached pages."),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
    '#default_value' => isset($settings['is_ajax']) ? $settings['is_ajax'] : 0,
  );

  $form['block_settings']['ajaxblocks']['loader_picture'] = array(
    '#type' => 'radios',
    '#title' => t('Loading throbber'),
    '#description' => t('Choose to display a loading throbber while it is loading.'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
    '#default_value' => isset($settings['loader_picture']) ? $settings['loader_picture'] : 0,
  );

  $form['block_settings']['ajaxblocks']['is_late'] = array(
    '#type' => 'radios',
    '#title' => t('JavaScript event which initiates block loading'),
    '#options' => array(
      0 => t('As soon as possible'),
      1 => t('After all assets are loaded'),
    ),
    '#default_value' => isset($settings['is_late']) ? $settings['is_late'] : 0,
  );
  $form['block_settings']['ajaxblocks']['is_late'][0]['#description'] = t('Will load block as soon as possible using the DOM.ready event.');
  $form['block_settings']['ajaxblocks']['is_late'][1]['#description'] = t('Will load block will wait until all assets (like web fonts, images) are loaded, using the window.onload event.');

  $form['block_settings']['ajaxblocks']['delay'] = array(
    '#type' => 'textfield',
    '#size' => 6,
    '#maxlength' => 6,
    '#title' => t('Time in milliseconds to wait before block loading'),
    '#description' => t('You can defer block loading and create interesting effects if necessary.'),
    '#default_value' => isset($settings['delay']) ? intval($settings['delay']) : 0,
  );

  $form['block_settings']['ajaxblocks']['include_noscript'] = array(
    '#type' => 'radios',
    '#title' => t('Include NOSCRIPT tag with original block content'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
    '#default_value' => isset($settings['include_noscript']) ? $settings['include_noscript'] : 1,
  );
  $form['block_settings']['ajaxblocks']['include_noscript'][0]['#description'] = t('No fallback content if Javascript is not supported or disabled.');
  $form['block_settings']['ajaxblocks']['include_noscript'][1]['#description'] = t('Original block content included in HTML code of the pages if JavaScript is not supported or disabled. On cached pages, this content will be static.');

  $all_roles = user_roles();

  $form['block_settings']['ajaxblocks']['cached_roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Load the block on cached pages for these roles only'),
    '#description' => t('Only anonymous role is necessary to be selected for most cases.'),
    '#options' => $all_roles,
    '#default_value' => isset($settings['cached_roles']) ? $settings['cached_roles'] : array('anonymous'),
  );

  $form['block_settings']['ajaxblocks']['uncached_roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Load the block on uncached pages for these roles only'),
    '#description' => t("Don't select any role unless you use authcache module or want to load this block via AJAX even on uncached pages."),
    '#options' => $all_roles,
    '#default_value' => isset($settings['uncached_roles']) ? $settings['uncached_roles'] : array(),
  );

  $form['#submit'][] = 'ajaxblocks_save_settings';
}

/**
 * Additional submit handler for block settings form. Saves AJAX settings for the block.
 */
function ajaxblocks_save_settings($form, &$form_state) {
  if (!isset($form_state['values']['block_settings'])) {
    return;
  }

  $config = config('ajaxblocks.settings');

  $class_name = get_class($form_state['block']);
  $module = $form_state['block']->module;
  $delta = $form_state['block']->delta;
  $uuid = isset($form_state['block']->uuid) ? $form_state['block']->uuid : '';
  $settings = $form_state['values']['block_settings']['ajaxblocks'];
  $settings['class_name'] = $class_name;

  if (!empty($settings['is_ajax'])) {
    $config->set($module . ':' . $delta . ':' . $uuid, $settings);
  }
  else {
    $config->clear($module . ':' . $delta . ':' . $uuid);
  }
  $config->save();
}

/**
 * Returns TRUE if the block is configured to be loaded via AJAX.
 * Block specific settings are also returned.
 */
function ajaxblocks_is_ajax($block_id, &$settings) {
  static $ajax_blocks = NULL;

  if (is_null($ajax_blocks)) {
    $ajax_blocks = config_get('ajaxblocks.settings');
  }
  if (array_key_exists($block_id, $ajax_blocks)) {
    $settings = $ajax_blocks[$block_id];
    return TRUE;
  }
  $settings = array();
  return FALSE;
}

/**
 * Handles AJAX request and returns the content of the appropriate blocks.
 */
function ajaxblocks_ajax_handler() {
  // Disable client-side caching.
  header('Cache-Control: private, no-cache, no-store, must-revalidate, max-age=0');
  header('Pragma: no-cache');
  // Disable server-side caching.
  backdrop_page_is_cacheable(FALSE);

  _ajaxblocks_in_ajax_handler_impl(TRUE);
  $content = array();
  $delays = array();
  $min_delay = 1000000;
  //$current_user_rids = $GLOBALS['user']->roles;
  if (isset($_GET['blocks']) && isset($_GET['path'])) {
    // Set 'q' parameter in order to make arg() work correctly.
    $_GET['q'] = $_GET['path'];
    $_REQUEST['q'] = $_GET['path'];
    // Set $_SERVER variables in order to make request_uri() work correctly.
    _ajaxblocks_fix_request_uri($_GET['path']);

    // Build the block content and return as json.
    $ajax_blocks = explode('/', $_GET['blocks']);
    unset($_GET['blocks']);
    unset($_GET['path']);
    unset($_GET['nocache']);
    $block_settings = array();
    foreach ($ajax_blocks as $block_id) {
      if (!ajaxblocks_is_ajax($block_id, $block_settings)) {
        continue;
      }
      // Don't return blocks which are not enabled for the current user.
      // TODO Check permissions fully.
      // if ((count($block_settings['role_permission']) > 0) && (count(array_intersect($current_user_rids, $block_settings['role_permission'])) == 0)) {
      //   continue;
      // }
      $delay = intval($block_settings['delay']);
      $delays[$block_id] = $delay;
      if ($min_delay > $delay) {
        $min_delay = $delay;
      }
      // Backdrop.settings can be changed by the block construction code. The handler returns the settings difference to the client.
      $settings_old = array();
      $js = backdrop_add_js();
      if (array_key_exists('settings', $js)) {
        $settings_old = $js['settings']['data'];
      }
      $parts = explode(":", $block_id);
      $block = new stdClass();
      $block->module = $parts[0];
      $block->delta = $parts[1];
      $infos = module_invoke($block->module, 'block_info');
      $block = _ajaxblocks_block($block->module, $block->delta, $infos[$block->delta]);
      // @todo only works with legacy blocks, so not Views blocks or even text blocks.
      if ($block_settings['class_name'] == 'BlockLegacy') {
        $block = new BlockLegacy($block->module . ':' . $block->delta, array());
      }
      else {
        $block = new $block->class($block->module . ':' . $block->delta, array());
      }
      $block->prepare();
      // $block_content = module_invoke($block->module, 'block_view', $block->delta);
      $block_content = $block->getContent();

      if (is_string($block_content)) {
        $block_content = array(
          '#markup' => $block_content,
        );
      }

      $data = array(
        'title' => $block->getTitle(),
        'content' => $block_content,
      );

      // Allow modules to modify the block before it is viewed, via either
      // hook_block_view_alter() or hook_block_view_MODULE_DELTA_alter().
      backdrop_alter(array('block_view', "block_view_{$block->module}_" . str_replace('-', '_', $block->delta)), $data, $block);
      $content[$block_id] = array(
        'content' => $data['content']['#markup'],
      );

      $settings_new = array();
      $js = backdrop_add_js();
      if (array_key_exists('settings', $js)) {
        $settings_new = $js['settings']['data'];
      }
      $array_mapping_func = (function_exists('backdrop_array_diff_assoc_recursive')) ? 'backdrop_array_diff_assoc_recursive' : 'array_diff_assoc';
      $settings_diff = call_user_func_array($array_mapping_func, array($settings_new, $settings_old));
      $content[$block_id]['ajaxblocks_settings'] = '';
      if (count($settings_diff) > 0) {
        $content[$block_id]['ajaxblocks_settings'] = call_user_func_array('array_merge_recursive', $settings_diff);
      }
    }
  }
  foreach ($delays as $block_id => $delay) {
    $delay -= $min_delay;
    if ($delay > 0) {
      $content[$block_id]['delay'] = $delay;
    }
  }
  backdrop_json_output($content);
}

/**
 * Helper to create a pretty block object from a moddelta.
 */
function _ajaxblocks_block($module, $delta, $info = NULL) {
  if (!$info) {
    $infos = module_invoke($module, 'block_info');
    $info = @$infos[$delta];
  }

  if ($info) {
    $info = compact('module', 'delta') + $info;
    $info['info'] = trim($info['info']);

    return (object) $info;
  }
}

/**
 * Returns TRUE if current page will be cached (for anonymous or for authenticated users)
 * by Backdrop core or by contrib modules (boost and authcache are supported).
 */
function ajaxblocks_page_cacheable() {
  static $page_cacheable = NULL;
  if (!is_null($page_cacheable)) {
    return $page_cacheable;
  }
  if (!backdrop_page_is_cacheable()) {
    $page_cacheable = FALSE;
    return $page_cacheable;
  }
  if ((module_exists('boost')) && (isset($GLOBALS['_boost'])) && (isset($GLOBALS['_boost']['cache_this'])) && ($GLOBALS['_boost']['cache_this'])) {
    //TODO check 403 and 404 for Boost: boost_get_http_status 403 404 for anon -> uncached
    $page_cacheable = TRUE;
    return $page_cacheable;
  }
  if ((module_exists('authcache')) && (isset($GLOBALS['is_page_authcache'])) && ($GLOBALS['is_page_authcache'])) {
    //TODO check 403 and 404 for authcache:  (variable_get('authcache_http200', FALSE) && _authcache_get_http_status() != 200)
    $page_cacheable = TRUE;
    return $page_cacheable;
  }
  $page_cacheable = (($GLOBALS['user']->uid == 0) && (config_get('system.core', 'cache')));
  return $page_cacheable;
}

/**
 * Stores AJAX block IDs temporarily to pass them from ajaxblocks_preprocess_block() to ajaxblocks_preprocess_page().
 */
function ajaxblocks_page_ajax_list($block_id = NULL, $settings = array()) {
  static $ajax_blocks = array();

  if (!is_null($block_id)) {
    $ajax_blocks[$block_id] = $settings;
  }

  return $ajax_blocks;
}

/**
 * Implements hook_preprocess_block().
 */
function ajaxblocks_preprocess_block(&$variables) {
  if (ajaxblocks_in_ajax_handler()) {
    return;
  }

  $id = $variables['block']->module . ':' . $variables['block']->delta . ':' . $variables['block']->uuid;
  $settings = array();
  if (!ajaxblocks_is_ajax($id, $settings)) {
    return;
  }

  $current_user_rids = $GLOBALS['user']->roles;
  if ((ajaxblocks_page_cacheable())) {
    if (count(array_intersect($current_user_rids, $settings['cached_roles'])) == 0) {
      return;
    }
  }
  else {
    if (count(array_intersect($current_user_rids, $settings['uncached_roles'])) == 0) {
      return;
    }
  }

  ajaxblocks_page_ajax_list($id, $settings);
  $noscript = '';
  if ($settings['include_noscript']) {
    $noscript = '<script type="text/javascript"></script><noscript>' . $variables['content']['#markup'] . '</noscript>';
  }
  $wrapper_class = "ajaxblocks-wrapper";
  if ($settings['loader_picture']) {
    $wrapper_class = "ajaxblocks-wrapper-" . intval($settings['loader_picture']);
  }

  $variables['content']['#markup'] = '<div id="block-' . $id . '-ajax-content" class="' . $wrapper_class . '">' . $noscript . '</div>';
}

/**
 * Implements hook_preprocess_page().
 */
function ajaxblocks_preprocess_page(&$variables) {
  $ajax_blocks = ajaxblocks_page_ajax_list();
  if (count($ajax_blocks) == 0) {
    return;
  }
  backdrop_add_js(backdrop_get_path('module', 'ajaxblocks') . '/ajaxblocks.js');
  $path = url('ajaxblocks');
  if ($path !== base_path() . 'ajaxblocks') {
    // Provide path for AJAX handler directly in non-trivial cases (for instance, language prefix).
    backdrop_add_js(array('ajaxblocks_path' => $path), 'setting');
  }
  $block_ids = array();
  $block_ids_late = array();
  $min_delay = 1000000;
  $min_delay_late = 1000000;
  $use_loader_picture = FALSE;
  foreach ($ajax_blocks as $block_id => $settings) {
    if ($settings['is_late']) {
      $block_ids_late[] = $block_id;
      if ($min_delay_late > $settings['delay']) {
        $min_delay_late = intval($settings['delay']);
      }
    }
    else {
      $block_ids[] = $block_id;
      if ($min_delay > $settings['delay']) {
        $min_delay = intval($settings['delay']);
      }
    }
    if ($settings['loader_picture'] > 0) {
      $use_loader_picture = TRUE;
    }
  }
  if ($use_loader_picture) {
    backdrop_add_css(backdrop_get_path('module', 'ajaxblocks') . '/ajaxblocks.css');
    $variables['styles'] = backdrop_get_css();
  }
  $get_copy = $_GET;
  $params_to_exclude = array('q', 'blocks', 'path');
  foreach ($params_to_exclude as $param) {
    unset($get_copy[$param]);
  }
  $get_params = backdrop_http_build_query($get_copy);
  if (strlen($get_params) > 0) {
    $get_params = '&' . $get_params;
  }

  if (count($block_ids) > 0) {
    backdrop_add_js(array('ajaxblocks' => 'blocks=' . implode('/', $block_ids) . '&path=' . $_GET['q'] . $get_params), 'setting');
    if ($min_delay > 0) {
      backdrop_add_js(array('ajaxblocks_delay' => $min_delay), 'setting');
    }
  }
  if (count($block_ids_late) > 0) {
    backdrop_add_js(array('ajaxblocks_late' => 'blocks=' . implode('/', $block_ids_late) . '&path=' . $_GET['q'] . $get_params), 'setting');
    if ($min_delay_late > 0) {
      backdrop_add_js(array('ajaxblocks_delay_late' => $min_delay_late), 'setting');
    }
  }
}

/**
 * Internal function which sets and returns the flag indicating whether current operation is block loading via AJAX.
 */
function _ajaxblocks_in_ajax_handler_impl($set = FALSE) {
  static $in_ajax_handler = FALSE;
  if ($set) {
    $in_ajax_handler = TRUE;
  }
  return $in_ajax_handler;
}

/**
 * Returns TRUE if current operation is block loading via AJAX.
 * May be used by other modules in hook_block() implementations to decide what version of block to return.
 */
function ajaxblocks_in_ajax_handler() {
  return _ajaxblocks_in_ajax_handler_impl();
}

/**
 * Internal function which makes request_uri() return correct value when handling AJAX request.
 */
function _ajaxblocks_fix_request_uri($path) {
  if (isset($_SERVER['REQUEST_URI'])) {
    $_SERVER['REQUEST_URI'] = '/' . $path;
  }
  // TODO support other ways to fix request_uri().
}
