<?php

/**
 * @file
 * Loads dynamic blocks on cached page for anonymous users by performing AJAX request.
 */

/**
 * Implements hook_menu().
 */
function ajaxblocks_menu() {
  $items = array();
  $items['ajaxblocks'] = array(
    'page callback' => 'ajaxblocks_ajax_handler',
    'delivery callback' => 'ajaxblock_deliver',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_config_info().
 */
function ajaxblocks_config_info() {
  $prefixes['jaxblocks.settings'] = array(
    'label' => t('Ajax Blocks settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_library_info().
 *
 */
function ajaxblocks_library_info() {
  $libraries['htmx'] = array(
    'title' => 'HTMX',
    'website' => 'http://htmx.org',
    'version' => '2.0.4',
    'js' => array(
      backdrop_get_path('module', 'ajaxblocks') . '/js/htmx.min.js' => array(),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Adds AJAX settings to the block configure page.
 */
function ajaxblocks_form_layout_block_configure_form_alter(&$form, &$form_state) {
  // Retrieve current setting for this block.
  $block = $form_state['block'];
  $settings = config_get('ajaxblocks.settings', $block->module . ':' . $block->delta . ':' . $block->uuid);

  $form['block_settings']['ajaxblocks'] = array(
    '#type' => 'fieldset',
    '#title' => t('AJAX settings'),
    '#description' => t('The settings for loading the block via AJAX request made after the page loading. This method is used for anonymous user only, and the whole page must be cached.'),
    '#weight' => 60,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'visibility',
  );

  if (module_exists('authcache')) {
    $form['block_settings']['ajaxblocks']['warning'] = array(
      '#type' => 'markup',
      '#value' => t('Authcache module is installed. Please check <a href="@settings">settings</a> and make sure it does not cache AJAX requests to page (Backdrop path) "ajaxblocks".',
        array('@settings' => url('admin/config/development/performance/authcache'))),
    );
  }

  $form['block_settings']['ajaxblocks']['is_ajax'] = array(
    '#type' => 'radios',
    '#title' => t('Load block via AJAX'),
    '#description' => t("Select 'yes' if this block has dynamic content and isn't displayed correctly on cached pages."),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
    '#default_value' => isset($settings['is_ajax']) ? $settings['is_ajax'] : 0,
  );

  $form['block_settings']['ajaxblocks']['is_late'] = array(
    '#type' => 'radios',
    '#title' => t('JavaScript event which initiates block loading'),
    '#options' => array(
      0 => t('As soon as possible'),
      1 => t('When block is in view'),
    ),
    '#default_value' => isset($settings['is_late']) ? $settings['is_late'] : 0,
  );
  $form['block_settings']['ajaxblocks']['is_late'][0]['#description'] = t('Will load block as soon as the page is loaded.');
  $form['block_settings']['ajaxblocks']['is_late'][1]['#description'] = t('Will load block will wait until the block is revealed in the viewport.');

  $form['block_settings']['ajaxblocks']['delay'] = array(
    '#type' => 'textfield',
    '#size' => 6,
    '#maxlength' => 6,
    '#title' => t('Time in milliseconds to wait before block loading'),
    '#description' => t('You can defer block loading and create interesting effects if necessary.'),
    '#default_value' => isset($settings['delay']) ? intval($settings['delay']) : 0,
  );

  $form['block_settings']['ajaxblocks']['reload'] = array(
    '#type' => 'select',
    '#title' => t('Reload'),
    '#description' => t('Choose to reload the block every few seconds.'),
    '#options' => array(0 => t('Never')) + backdrop_map_assoc(array(5, 10, 20, 60, 300, 1800, 3600), 'format_interval'),
    '#default_value' => isset($settings['reload']) ? $settings['reload'] : 0,
  );

  $all_roles = user_roles();

  $form['block_settings']['ajaxblocks']['cached_roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Load the block on cached pages for these roles only'),
    '#description' => t('Only anonymous role is necessary to be selected for most cases.'),
    '#options' => $all_roles,
    '#default_value' => isset($settings['cached_roles']) ? $settings['cached_roles'] : array('anonymous'),
  );

  $form['block_settings']['ajaxblocks']['uncached_roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Load the block on uncached pages for these roles only'),
    '#description' => t("Don't select any role unless you use authcache module or want to load this block via AJAX even on uncached pages."),
    '#options' => $all_roles,
    '#default_value' => isset($settings['uncached_roles']) ? $settings['uncached_roles'] : array(),
  );

  $form['#submit'][] = 'ajaxblocks_save_settings';
}

/**
 * Additional submit handler for block settings form.
 * Saves AJAX settings for the block.
 */
function ajaxblocks_save_settings($form, &$form_state) {
  if (!isset($form_state['values']['block_settings'])) {
    return;
  }

  $config = config('ajaxblocks.settings');

  $class_name = get_class($form_state['block']);
  $module = $form_state['block']->module;
  $delta = $form_state['block']->delta;
  $uuid = isset($form_state['block']->uuid) ? $form_state['block']->uuid : '';
  $settings = $form_state['values']['block_settings']['ajaxblocks'];
  $settings['class_name'] = $class_name;

  if (!empty($settings['is_ajax'])) {
    $config->set($module . ':' . $delta . ':' . $uuid, $settings);
  }
  else {
    $config->clear($module . ':' . $delta . ':' . $uuid);
  }
  $config->save();
}

/**
 * Returns TRUE if the block is configured to be loaded via AJAX.
 * Block specific settings are also returned.
 *
 * @param string $block_id
 * @param array $settings
 *
 * @return bool
 */
function ajaxblocks_is_ajax($block_id, &$settings) {
  static $ajax_blocks = NULL;

  if (is_null($ajax_blocks)) {
    $ajax_blocks = config_get('ajaxblocks.settings');
  }
  if (array_key_exists($block_id, $ajax_blocks)) {
    $settings = $ajax_blocks[$block_id];
    return TRUE;
  }
  $settings = array();
  return FALSE;
}

/**
 * Handles AJAX request and returns the content of the appropriate blocks.
 *
 * @return string
 */
function ajaxblocks_ajax_handler() {
  $block_id = $_GET['block_id'] ?? NULL;
  $class_name = $_GET['block_class_name'] ?? NULL;
  if (!$block_id) {
    return '';
  }
  // Disable client-side caching.
  header('Cache-Control: private, no-cache, no-store, must-revalidate, max-age=0');
  header('Pragma: no-cache');
  // Disable page caching.
  backdrop_page_is_cacheable(FALSE);

  $parts = explode(":", $block_id);
  $block = new stdClass();
  $block->module = $parts[0];
  $block->delta = $parts[1];
  $infos = module_invoke($block->module, 'block_info');
  $block = _ajaxblocks_block($block->module, $block->delta, $infos[$block->delta]);
  if ($class_name == 'BlockLegacy') {
    $block = new BlockLegacy($block->module . ':' . $block->delta, array());
  }
  else {
    $block = new $block->class($block->module . ':' . $block->delta, array());
  }
  $block->prepare();

  $block_content = $block->getContent();

  if (is_string($block_content)) {
    $block_content = array(
      '#markup' => $block_content,
    );
  }

  $data = array(
    'title' => $block->getTitle(),
    'content' => $block_content,
  );

  // Allow modules to modify the block before it is viewed, via either
  // hook_block_view_alter() or hook_block_view_MODULE_DELTA_alter().
  backdrop_alter(array('block_view', "block_view_{$block->module}_" . str_replace('-', '_', $block->delta)), $data, $block);

  // Only updating the block content, ignore the title.
  return backdrop_render($data['content']);
}

/**
 * Delivery callback for block results.
 *
 * @see ajaxblocks_ajax_handler()
 */
function ajaxblock_deliver($page_callback_result) {
  backdrop_add_http_header('Content-Type', 'text/html; charset=utf-8');

  // Send appropriate language header for browsers.
  global $language;
  backdrop_add_http_header('Content-Language', $language->langcode);

  // The page callback is always ajaxblocks_ajax_handler(), which always returns
  // a string, and is only accessed when the user actually has access to it.
  // Therefore, we do not care for the other possible page callback results.
  print $page_callback_result;

  // Perform end-of-request tasks. The page cache is created here.
  backdrop_page_footer();
}

/**
 * Helper to create a pretty block object from a moddelta.
 *
 * @param string $module
 * @param string $delta
 * @param array|null $info
 *
 * @return object
 */
function _ajaxblocks_block($module, $delta, $info = NULL) {
  if (!$info) {
    $infos = module_invoke($module, 'block_info');
    $info = @$infos[$delta];
  }

  if ($info) {
    $info = compact('module', 'delta') + $info;
    $info['info'] = trim($info['info']);

    return (object) $info;
  }
}

/**
 * Returns TRUE if current page will be cached (for anonymous or for authenticated users)
 * by Backdrop core or by contrib modules (boost and authcache are supported).
 *
 * @return bool
 */
function ajaxblocks_page_cacheable() {
  static $page_cacheable = NULL;
  if (!is_null($page_cacheable)) {
    return $page_cacheable;
  }
  if (!backdrop_page_is_cacheable()) {
    $page_cacheable = FALSE;
    return $page_cacheable;
  }
  if ((module_exists('boost')) && (isset($GLOBALS['_boost'])) && (isset($GLOBALS['_boost']['cache_this'])) && ($GLOBALS['_boost']['cache_this'])) {
    //TODO check 403 and 404 for Boost: boost_get_http_status 403 404 for anon -> uncached
    $page_cacheable = TRUE;
    return $page_cacheable;
  }
  if ((module_exists('authcache')) && (isset($GLOBALS['is_page_authcache'])) && ($GLOBALS['is_page_authcache'])) {
    //TODO check 403 and 404 for authcache:  (variable_get('authcache_http200', FALSE) && _authcache_get_http_status() != 200)
    $page_cacheable = TRUE;
    return $page_cacheable;
  }
  $page_cacheable = (($GLOBALS['user']->uid == 0) && (config_get('system.core', 'cache')));
  return $page_cacheable;
}

/**
 * Implements hook_preprocess_block().
 */
function ajaxblocks_preprocess_block(&$variables) {
  $id = $variables['block']->module . ':' . $variables['block']->delta . ':' . $variables['block']->uuid;
  $settings = array();
  if (!ajaxblocks_is_ajax($id, $settings)) {
    return;
  }

  $current_user_rids = $GLOBALS['user']->roles;
  if ((ajaxblocks_page_cacheable())) {
    if (count(array_intersect($current_user_rids, $settings['cached_roles'])) == 0) {
      return;
    }
  }
  else {
    if (count(array_intersect($current_user_rids, $settings['uncached_roles'])) == 0) {
      return;
    }
  }

  $trigger_vals = array();
  if ($settings['is_late']) {
    $trigger_vals[] = 'revealed';
  }
  else {
    $trigger_vals[] = 'load';
  }
  if ($settings['reload']) {
    $trigger_vals[] = 'every ' . $settings['reload'] . 's';
  }

  $variables['attributes']['hx-get'] = '/ajaxblocks';
  $variables['attributes']['hx-target'] = 'find .block-content';
  $variables['attributes']['hx-trigger'] = implode(', ', $trigger_vals);
  $variables['attributes']['hx-vals'] = json_encode(array(
    'block_id' => $id,
    'block_class_name' => $settings['class_name'],
  ));

}

/**
 * Implements hook_preprocess_page().
 */
function ajaxblocks_preprocess_page(&$variables) {
  backdrop_add_library('ajaxblocks', 'htmx', TRUE);
}
